### ISSUE TITLE
`declare module '@vue/runtime-core'` Ломает глобальную типизацию в компонентах Vue

### ISSUE THREAD

**Issue by DiFuks** [bezumkin/vesp-frontend#4]
При расширении глобальных типов `vue` существует проблема:

Если расширять модуль `@vue/runtime-core`, ломаются все глобальные типы, которые расширяли `vue`. В том числе все автоматически сгенерированные типы из `.nuxt/types/imports.d.ts`. При этом, если хотя бы одна библиотека расширяет `@vue/runtime-core`, а не `vue`, ломаются глобальные типы у всех библиотек, которые расширяли `vue`. А это — сам nuxt, i18n, vue-router и т.д.

Ссылки для ознакомления:
https://nuxt.com/blog/v3-13#vue-typescript-changes (здесь также описан workaround)
https://github.com/nuxt/nuxt/pull/28542#issuecomment-2293282891
https://github.com/nuxt/nuxt/issues/28707
https://github.com/vuejs/language-tools/issues/3178

Участок, кода, где требуется исправление:

https://github.com/bezumkin/vesp-frontend/blob/f35eea5353e38d141d3ba848a833b466387084fb/src/module.ts#L189-L194

Если будет удобнее — я могу принести PR

**Comment by bezumkin** [comment]
@DiFuks Да, конечно, присылайте PR, с удовольствием посмотрю.

Я в Typescript вообще не эксперт, только учусь, и в основном делаю так, чтобы PhpStorm не ругался.

**Comment by DiFuks** [comment]
@bezumkin https://github.com/bezumkin/vesp-frontend/pull/5

**Comment by DiFuks** [comment]
Уточню, что данная проблема наблюдается и в зависимостях `@vesp/frontend`, а именно:

- `pinia`. Но разработчики [исправили это](https://github.com/vuejs/pinia/commit/8a6ce86db83b6315c067c8a98c898b3c74efe62e#diff-094806c433011456914201ea662b339b53b9b1236f3226c1da3fd807106ad8a8R43). Поднятие версии в проекте исправляет это. Но, когда я изучал зависимости проекта, задумался — точно ли `pinia` должна быть прямой зависимостью, а не `peer`? Если пользователь `@vesp/frontend` поднимет версию `pinia` в своём проекте, но не поднимет в `package-lock` файле, `@vesp/frontend` и приложение будут использовать разные версии `pinia`. И это может привести к непредвиденным обстоятельствам

- `bootstrap-vue-next`. Разработчики [исправили эту проблему](https://github.com/bootstrap-vue-next/bootstrap-vue-next/compare/bootstrapvuenext-v0.24.12...bootstrapvuenext-v0.24.13#diff-8495e7994841a02ea9fafa741445133b253a789261f1caf5aa3df15f71972b0b), начиная с версии `0.24.13`. Но, к сожалению, `@versp/frontend` жёстко завязан на версии `0.18.*`

**Comment by bezumkin** [comment]
@DiFuks 

> жёстко завязан на версии `0.18.*`

Да, потому что там дальше были странные проблемы с серверным рендером. Я несколько раз пробовал обновиться, но встречался со всяким странным, например dropdown с ssr не работал.

Надо обновляться и разбираться - надеюсь, на праздниках это сделать. Обновлю vesp-frontend и подтяну его в Орбиту и Сасфликс.
